In [32]:
def transponse(matrix): # Транспонирование матрицы
    return [[matrix[j, i] for j in range(n)] for i in range(n)]

def determinant(matrix): # Определитель матрицы
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0

    for j in range(len(matrix)):
        submatrix = []

        for i in range(1, len(matrix)):
            row = []
            for k in range(len(matrix)):
                if k != j:
                    row.append(matrix[i][k])
            submatrix.append(row)

        sub_det = determinant(submatrix)

        det += (-1) ** j * matrix[0][j] * sub_det

    return det

def matrix_norm(matrix): # Норма матрицы, наверное, первая
    column_sums = np.zeros(n)
    
    for j in range(n):
        for i in range(n):
            column_sums[j] += abs(matrix[i][j])
    
    norm = max(column_sums)
    return norm

print(f"Обратная матрица к A: {np.linalg.inv(a)}") 
print(f"Определитель матрицы A: {determinant(a)}")
A_n = np.dot(a, transponse(a))
print(f"Число обусловленности для A: {matrix_norm(a) * matrix_norm(np.linalg.inv(a))}")
print(f"Число обусловленности для A: {matrix_norm(a) * matrix_norm(np.linalg.inv(a))}")
print(f"Число обусловленности для A*A.T: {matrix_norm(A_n) * matrix_norm(np.linalg.inv(A_n))}")

Обратная матрица к A: [[ 2.33635850e-02 -6.70058463e-05 -4.78196227e-03 -4.39143488e-03
  -6.22524886e-03 -2.66158074e-03  1.76200363e-03 -8.19351934e-06]
 [-4.86254825e-03  2.88906815e-02 -2.89354987e-04 -3.50589935e-03
  -4.54788246e-03 -4.47524392e-04  1.56518956e-03 -2.64830414e-03]
 [ 3.32300284e-04 -7.39315682e-03  3.90273636e-02 -4.57700965e-03
  -3.21668298e-03  1.08402472e-03 -1.45238350e-03 -8.58366373e-04]
 [-2.34441511e-03 -1.70046810e-03 -6.84705910e-03  2.72497170e-02
   3.66129483e-03 -1.84460378e-03 -4.10078091e-03 -4.89720535e-03]
 [ 5.72050761e-04  1.22128681e-04 -4.32666568e-03  1.34363392e-03
   3.73572597e-02 -6.23633452e-03 -4.49298715e-03 -5.01963342e-03]
 [-3.13834384e-03 -4.63671723e-03 -1.72855498e-03 -1.69630333e-03
  -4.33233930e-03  2.63591964e-02  5.94692819e-04 -1.16620888e-03]
 [-3.83860190e-03  5.61258340e-05 -3.16233271e-03 -3.19822385e-03
  -7.37644250e-03  7.46481207e-04  2.68161410e-02  7.47700391e-04]
 [ 1.55280036e-03 -1.33618639e-04 -4.46082671e-

In [27]:
# Прямой ход схемы единственного деления
A = a.copy()
B = b.copy()

for i in range(n):
    if A[i, i] == 0:
        print('Деление на ноль невозможно')
        break

    for k in range(i + 1, n):
        q = A[k, i] / A[i, i]

        for j in range(n):
            A[k, j] -= q * A[i, j]
        B[k] -= q * B[i]        

print(A) # Вывод получившейся матрицы

[[ 4.51400000e+01  4.18000000e+00  9.13000000e+00  9.94000000e+00
   9.42000000e+00  7.34000000e+00  5.20000000e-01  3.61000000e+00]
 [ 0.00000000e+00  3.59377093e+01  2.43315463e+00  5.60350022e+00
   5.08957466e+00  2.32387240e+00  6.39255649e-02  4.47302171e+00]
 [ 0.00000000e+00  0.00000000e+00  2.72266174e+01  5.02544164e+00
   2.69761843e+00 -1.25285853e-01  2.84187230e+00  1.73320470e+00]
 [ 8.88178420e-16  0.00000000e+00  0.00000000e+00  3.84117079e+01
  -1.38503797e+00  2.44721747e+00  6.02392323e+00  5.25092730e+00]
 [ 2.15841118e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.93621547e+01  7.01908382e+00  5.13266687e+00  4.43853780e+00]
 [-9.72146327e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.80226006e+01 -7.34116272e-01  1.31315056e+00]
 [-1.62587687e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00
   8.88178420e-16  0.00000000e+00  3.72233339e+01 -8.14134663e-01]
 [-1.47914474e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -

In [28]:
# Обратный ход схемы единственного деления
x1 = np.zeros((n, 1), dtype='float')
x1[n - 1] = B[n - 1, 0] / A[n - 1, n - 1]

for i in range(n - 2, -1, -1):
    sum = 0

    for j in range(i + 1, n):
        sum += A[i, j] * x1[j]

    x1[i] = (B[i, 0] - sum) / A[i, i]

x1 = np.reshape(x1, (n, 1))
print(x)

print(f"Решение схемой единственного деления: {x1}")

[[2.28]
 [5.25]
 [5.07]
 [1.2 ]
 [2.4 ]
 [6.09]
 [5.11]
 [4.04]]
Решение схемой единственного деления: [[2.27990117]
 [5.25031941]
 [5.06933156]
 [1.20029998]
 [2.40015948]
 [6.09026875]
 [5.1096017 ]
 [4.04040979]]


In [18]:
# Прямой ход метода вращений
def givens_rotation(A, b):
    n = len(b)
    
    for i in range(n-1):
        for j in range(i+1, n):
            if A[j, i] != 0:
                cos_phi = A[i, i] / np.sqrt(A[i, i]**2 + A[j, i]**2)
                sin_phi = -A[j, i] / np.sqrt(A[i, i]**2 + A[j, i]**2)
                
                for k in range(i, n):
                    temp_aik = A[i, k]
                    temp_ajk = A[j, k]
                    A[i, k] = temp_aik * cos_phi - temp_ajk * sin_phi
                    A[j, k] = temp_aik * sin_phi + temp_ajk * cos_phi
                
                temp_b_i = b[i]
                temp_b_j = b[j]
                b[i] = temp_b_i * cos_phi - temp_b_j * sin_phi
                b[j] = temp_b_i * sin_phi + temp_b_j * cos_phi
    
    return A, b

# Копируем матрицу a и вектор b
A = np.copy(a)
B = np.copy(b)

A, B = givens_rotation(A, B)
print(f"{A}")
print(B)

[[ 8.62420431 11.40725526 10.95795004]
 [ 0.          4.98805848  2.72097185]
 [ 0.          0.          8.36742153]]
[[274.29332779]
 [  0.56051568]
 [ 21.0458341 ]]


In [19]:
#Обратный ход метода вращений, такой же, как у схемы единственного деления
x = np.zeros((n, 1), dtype='float')
x[n - 1] = B[n - 1, 0] / A[n - 1, n - 1]

for i in range(n - 2, -1, -1):
    sum = 0

    for j in range(i + 1, n):
        sum += A[i, j] * x[j]

    x[i] = (B[i, 0] - sum) / A[i, i]

x = np.reshape(x, (n, 1))

print(f"Решение, полученное методом вращений: {x}")

Решение, полученное методом вращений: [[30.27538841]
 [-1.25966923]
 [ 2.51521141]]


In [29]:
# Метод релаксации
A = a.copy()

def simmetry(A): # Необходимо выполнение условия симметричности
    for i in range(n):
        for j in range(n):
            if i != j:
                A[i, j] = A[j, i]
        diagonal_sum = np.sum(A[i]) - A[i, i]
        A[i, i] = diagonal_sum + 1
        
    return

simmetry(A)

def sum1(A, x, i, n):
    s = 0

    for j in range(i):
        s += A[i, j] * x[j]

    return s

def sum2(A, x, i, n):
    s = 0
    
    for j in range(i + 1, n):
        s += A[i, j] * x[j]
        
    return s

def relaxation_method(A, b, n, epsilon = 1e-4, max_iterations = 300, w = 1.5):
    x = np.zeros((n, 1))

    for _ in range(max_iterations):
        x_new = np.zeros_like(x)

        for i in range(n):
            x_new[i] = (1 - w) * x[i] + (w / A[i, i]) * (b[i] - sum1(A, x_new, i, n) - sum2(A, x, i, n))

        if np.max(np.abs(x_new - x)) < epsilon:
            return x_new

        x = x_new

    return x

print(f"Матрица А: {A}")
print(b - A @ relaxation_method(A, b, n))
print(f"Решение, полученное методом релаксации: {relaxation_method(A, b, n)}")

Матрица А: [[34.61  8.34  2.15  6.42  1.48  7.47  7.66  0.09]
 [ 8.34 38.63  7.71  5.65  2.54  8.3   2.5   2.59]
 [ 2.15  7.71 44.39  9.91  5.29  5.28  6.94  6.11]
 [ 6.42  5.65  9.91 44.83  1.86  6.07  7.38  6.54]
 [ 1.48  2.54  5.29  1.86 36.96  7.79  9.98  7.02]
 [ 7.47  8.3   5.28  6.07  7.79 41.62  2.38  3.33]
 [ 7.66  2.5   6.94  7.38  9.98  2.38 42.74  4.9 ]
 [ 0.09  2.59  6.11  6.54  7.02  3.33  4.9  31.58]]
[[-0.00093722]
 [-0.00105682]
 [-0.00155996]
 [-0.0008676 ]
 [-0.0007312 ]
 [ 0.00013331]
 [ 0.00045225]
 [ 0.00054189]]
Решение, полученное методом релаксации: [[3.79769214]
 [4.35037095]
 [1.72371335]
 [1.32372224]
 [1.4223416 ]
 [6.35240866]
 [4.92210723]
 [4.95042713]]


In [30]:
# Метод минимальных невязок
def minimal_residual_method(A, b, max_iterations=100, epsilon=1e-6):
    x = np.zeros(n)
    r = b - np.dot(A, x)

    for i in range(max_iterations):
        Ar = np.dot(A, r)
        alpha = np.dot(Ar, r) / np.dot(Ar, Ar)
        x = x + alpha * r
        r = b - np.dot(A, x)
        residual_norm = np.linalg.norm(r)

        if residual_norm < epsilon:
            break

    return x

def to_tuple(b): # Перевод столбца в tuple
    return [b[0, i] for i in range(n)]

print(b - A @ relaxation_method(A, b, n))
print("Решение x:", minimal_residual_method(A, to_tuple(b.reshape((1, n)))).reshape((n, 1)))

Решение x: [[3.79766547]
 [4.35035244]
 [1.72367912]
 [1.32370648]
 [1.42231293]
 [6.3524285 ]
 [4.92213424]
 [4.95045585]]
